#!/usr/bin/env bash

set -e

# Install core
apt-get update -y
apt-get dist-upgrade -y
apt-get install -y build-essential mosh python
apt-get autoremove -y

# Set up ufw
ufw allow ssh
ufw allow 60000:61000/udp
ufw enable

# Set up non-root user
mkdir -p /home/rockymadden/.ssh
cat <<EOT >> /home/rockymadden/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1doCgJj4PFO4jxgf2UnR8nmlNY7y96C6vp+oimSRZTijqy5qxHAE1GN8TNFFrnWEC/gQ2rD53rmLj5nEQr1v1oavKaOrSjmsWciytc+0WIfgB9PWLt17/yXtlgbFnHOcaWt7rD7WiJ2DzMfQGmrroHXZ8ukq47MaKwtg+dCajUzgFRDxBICZr53iBiCCUuTSjG5GcIPwKFRjZ/QVHmaFBMloPCfxj/uNYiDtnOAlOG0kkrLJWfHWCRGQDKsHGQpnd9mgGz40Gc/Fg/RUZzuP556KdI2vyoyoFkd6E0lhNuRLx3SPAhffPCyetEM9KWmk3FRgiOgVVOFgtmEp3Ykqe1rM/Y/PmjzfmKudWGPkFSTOd+656XTVCJuZJjEQOY4+IgUiryhXglZrLTg9+eH/VvJf4ruFRaqXpxkaAgTmQUwoKiiJ5xkq3Sj8DjQ9nIFB5/aHRq/9ao0wfmb8mMkG+5wgWrgE93xEwq+zLxCgW3hghnSX29Hglg1tck7fsNzai7IJaesQbo6VKvOoG87GcU7cXIqiEO3W987wffGI1hghCERzSmwZorMeFLU8B6D2adQi3DYvAzfOqP/zN4Mu5EYcK9GBCTjm3f22NZ+/4sNaJOIdzdff8kLGS4KSsG5HtAuswxFRgWNR6sMSc8PxlzWOdWfU1EEmKQ1VULw== dev@rockymadden.com
EOT
useradd -d /home/rockymadden rockymadden
usermod -aG sudo rockymadden
chown -R rockymadden:rockymadden /home/rockymadden/
chmod 700 /home/rockymadden/.ssh
chmod 644 /home/rockymadden/.ssh/authorized_keys
sed -i '/%sudo/c%sudo ALL=(ALL) NOPASSWD:ALL' /etc/sudoers

# Switch to non-root user
su -l rockymadden

# Install brew
curl -sSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh | sh
test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.profile

# Reload non-root user
exit
su -l rockymadden

# Install brew barebones
brew tap homebrew/bundle
brew install emacs git hub tmux zsh

# Install dotfiles
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/Brewfile --output Brewfile
chmod 644 Brewfile
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/Npmfile --output Npmfile
chmod 644 Npmfile
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/.gitconfig --output .gitconfig
chmod 644 .gitconfig
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/.gitignore --output .gitignore
chmod 644 .gitignore
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/.spacemacs --output .spacemacs
chmod 644 .spacemacs
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/.tmux.conf --output .tmux.conf
chmod 644 .tmux.conf
curl -sSL https://raw.githubusercontent.com/rockymadden/dotfiles/master/.zshrc --output .zshrc
chmod 644 .zshrc

# Install extras
git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
curl -sSL https://get.haskellstack.org/ | sh

# Clean up
brew cleanup
rm -rf $(brew --cache)
sudo apt-get clean

# Enable zsh
sudo chown -R rockymadden:rockymadden ~/
sudo usermod -s $(which zsh) rockymadden

set +e
